# version: '2'
# services:
#   web:
#     build: .
#     command: npm run dev
#     volumes:
#       - .:/usr/app/
#       - /usr/app/node_modules
#     ports:
#       - "3000:3000"    
    

version: '3.7'

services:
  acm-backend:
    image: aminepolytech/acm-backend:latest
    volumes:
      - C:/DockerVolumes/acm/logs:/logs
      - C:/DockerVolumes/acm/pdfs:/pdfs
      - C:/DockerVolumes/acm/Pieces:/Pieces
    ports:
      - "3000:3000"


# version: 4
# services:
#   acm-backend:
#     image: aminepolytech/acm-backend:latest
#     volumes:
#       - ${WEBAPP_STORAGE_HOME}/data/logs:/logs
#       - ${WEBAPP_STORAGE_HOME}/data/pdfs:/pdfs
#       - ${WEBAPP_STORAGE_HOME}/data/Pieces:/Pieces
#     restart: always