# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - acm-backend-2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_3cb6adfe32fc438ca0dbb18640dcb693 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_28c32296f2ac4bcc9d307e192bd27dc5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3cb6adfe32fc438ca0dbb18640dcb693 }}/acm-backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'acm-backend-2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b0566b98043e4ee38ebce5772dd926aa }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3cb6adfe32fc438ca0dbb18640dcb693 }}/acm-backend:${{ github.sha }}'